/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.manning.pulsar.iiot;

@org.apache.avro.specific.AvroGenerated
public interface SensorProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SensorProtocol\",\"namespace\":\"com.manning.pulsar.iiot\",\"types\":[{\"type\":\"record\",\"name\":\"ClutchSensor\",\"namespace\":\"com.manning.pulsar.iiot.clutch\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"int\"},{\"name\":\"bearing_1_temp\",\"type\":\"float\"},{\"name\":\"bearing_2_temp\",\"type\":\"float\"},{\"name\":\"bearing_3_temp\",\"type\":\"float\"},{\"name\":\"bearing_4_temp\",\"type\":\"float\"},{\"name\":\"bearing_5_temp\",\"type\":\"float\"},{\"name\":\"bearing_6_temp\",\"type\":\"float\"},{\"name\":\"thrust_bearing_temp\",\"type\":\"float\"},{\"name\":\"clutch_attitude\",\"type\":\"float\"}]},{\"type\":\"record\",\"name\":\"EngineSensor\",\"namespace\":\"com.manning.pulsar.iiot.engine\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"int\"},{\"name\":\"motor_sator_winding_temp\",\"type\":\"float\"},{\"name\":\"iron_temp\",\"type\":\"float\"},{\"name\":\"cooling_air_temp\",\"type\":\"float\"},{\"name\":\"air_temp\",\"type\":\"float\"},{\"name\":\"motor_power_supply_current\",\"type\":\"float\"}]},{\"type\":\"record\",\"name\":\"PumpSensor\",\"namespace\":\"com.manning.pulsar.iiot.pump\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"int\"},{\"name\":\"output_water_pressure\",\"type\":\"float\"},{\"name\":\"supply_water_pressure\",\"type\":\"float\"},{\"name\":\"temp_at_discharge_nozzle\",\"type\":\"float\"},{\"name\":\"water_flow_rate\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"OilCoolerSensor\",\"namespace\":\"com.manning.pulsar.iiot.oilcooler\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"int\"},{\"name\":\"lubricating_oil_temp\",\"type\":\"float\"},{\"name\":\"lubricating_oil_pressure\",\"type\":\"float\"},{\"name\":\"oil_temp_back\",\"type\":\"float\"},{\"name\":\"oil_temp_front\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SensorProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.manning.pulsar.iiot.SensorProtocol.PROTOCOL;
  }
}