/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.manning.pulsar.iiot.engine;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EngineSensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7856760375455018280L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EngineSensor\",\"namespace\":\"com.manning.pulsar.iiot.engine\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"int\"},{\"name\":\"motor_sator_winding_temp\",\"type\":\"double\"},{\"name\":\"iron_temp\",\"type\":\"double\"},{\"name\":\"cooling_air_temp\",\"type\":\"double\"},{\"name\":\"air_temp\",\"type\":\"double\"},{\"name\":\"motor_power_supply_current\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EngineSensor> ENCODER =
      new BinaryMessageEncoder<EngineSensor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EngineSensor> DECODER =
      new BinaryMessageDecoder<EngineSensor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EngineSensor> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EngineSensor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EngineSensor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EngineSensor>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EngineSensor to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EngineSensor from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EngineSensor instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EngineSensor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int sensor_id;
  @Deprecated public double motor_sator_winding_temp;
  @Deprecated public double iron_temp;
  @Deprecated public double cooling_air_temp;
  @Deprecated public double air_temp;
  @Deprecated public double motor_power_supply_current;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EngineSensor() {}

  /**
   * All-args constructor.
   * @param sensor_id The new value for sensor_id
   * @param motor_sator_winding_temp The new value for motor_sator_winding_temp
   * @param iron_temp The new value for iron_temp
   * @param cooling_air_temp The new value for cooling_air_temp
   * @param air_temp The new value for air_temp
   * @param motor_power_supply_current The new value for motor_power_supply_current
   */
  public EngineSensor(java.lang.Integer sensor_id, java.lang.Double motor_sator_winding_temp, java.lang.Double iron_temp, java.lang.Double cooling_air_temp, java.lang.Double air_temp, java.lang.Double motor_power_supply_current) {
    this.sensor_id = sensor_id;
    this.motor_sator_winding_temp = motor_sator_winding_temp;
    this.iron_temp = iron_temp;
    this.cooling_air_temp = cooling_air_temp;
    this.air_temp = air_temp;
    this.motor_power_supply_current = motor_power_supply_current;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_id;
    case 1: return motor_sator_winding_temp;
    case 2: return iron_temp;
    case 3: return cooling_air_temp;
    case 4: return air_temp;
    case 5: return motor_power_supply_current;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_id = (java.lang.Integer)value$; break;
    case 1: motor_sator_winding_temp = (java.lang.Double)value$; break;
    case 2: iron_temp = (java.lang.Double)value$; break;
    case 3: cooling_air_temp = (java.lang.Double)value$; break;
    case 4: air_temp = (java.lang.Double)value$; break;
    case 5: motor_power_supply_current = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return The value of the 'sensor_id' field.
   */
  public int getSensorId() {
    return sensor_id;
  }


  /**
   * Sets the value of the 'sensor_id' field.
   * @param value the value to set.
   */
  public void setSensorId(int value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'motor_sator_winding_temp' field.
   * @return The value of the 'motor_sator_winding_temp' field.
   */
  public double getMotorSatorWindingTemp() {
    return motor_sator_winding_temp;
  }


  /**
   * Sets the value of the 'motor_sator_winding_temp' field.
   * @param value the value to set.
   */
  public void setMotorSatorWindingTemp(double value) {
    this.motor_sator_winding_temp = value;
  }

  /**
   * Gets the value of the 'iron_temp' field.
   * @return The value of the 'iron_temp' field.
   */
  public double getIronTemp() {
    return iron_temp;
  }


  /**
   * Sets the value of the 'iron_temp' field.
   * @param value the value to set.
   */
  public void setIronTemp(double value) {
    this.iron_temp = value;
  }

  /**
   * Gets the value of the 'cooling_air_temp' field.
   * @return The value of the 'cooling_air_temp' field.
   */
  public double getCoolingAirTemp() {
    return cooling_air_temp;
  }


  /**
   * Sets the value of the 'cooling_air_temp' field.
   * @param value the value to set.
   */
  public void setCoolingAirTemp(double value) {
    this.cooling_air_temp = value;
  }

  /**
   * Gets the value of the 'air_temp' field.
   * @return The value of the 'air_temp' field.
   */
  public double getAirTemp() {
    return air_temp;
  }


  /**
   * Sets the value of the 'air_temp' field.
   * @param value the value to set.
   */
  public void setAirTemp(double value) {
    this.air_temp = value;
  }

  /**
   * Gets the value of the 'motor_power_supply_current' field.
   * @return The value of the 'motor_power_supply_current' field.
   */
  public double getMotorPowerSupplyCurrent() {
    return motor_power_supply_current;
  }


  /**
   * Sets the value of the 'motor_power_supply_current' field.
   * @param value the value to set.
   */
  public void setMotorPowerSupplyCurrent(double value) {
    this.motor_power_supply_current = value;
  }

  /**
   * Creates a new EngineSensor RecordBuilder.
   * @return A new EngineSensor RecordBuilder
   */
  public static com.manning.pulsar.iiot.engine.EngineSensor.Builder newBuilder() {
    return new com.manning.pulsar.iiot.engine.EngineSensor.Builder();
  }

  /**
   * Creates a new EngineSensor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EngineSensor RecordBuilder
   */
  public static com.manning.pulsar.iiot.engine.EngineSensor.Builder newBuilder(com.manning.pulsar.iiot.engine.EngineSensor.Builder other) {
    if (other == null) {
      return new com.manning.pulsar.iiot.engine.EngineSensor.Builder();
    } else {
      return new com.manning.pulsar.iiot.engine.EngineSensor.Builder(other);
    }
  }

  /**
   * Creates a new EngineSensor RecordBuilder by copying an existing EngineSensor instance.
   * @param other The existing instance to copy.
   * @return A new EngineSensor RecordBuilder
   */
  public static com.manning.pulsar.iiot.engine.EngineSensor.Builder newBuilder(com.manning.pulsar.iiot.engine.EngineSensor other) {
    if (other == null) {
      return new com.manning.pulsar.iiot.engine.EngineSensor.Builder();
    } else {
      return new com.manning.pulsar.iiot.engine.EngineSensor.Builder(other);
    }
  }

  /**
   * RecordBuilder for EngineSensor instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EngineSensor>
    implements org.apache.avro.data.RecordBuilder<EngineSensor> {

    private int sensor_id;
    private double motor_sator_winding_temp;
    private double iron_temp;
    private double cooling_air_temp;
    private double air_temp;
    private double motor_power_supply_current;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.manning.pulsar.iiot.engine.EngineSensor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.motor_sator_winding_temp)) {
        this.motor_sator_winding_temp = data().deepCopy(fields()[1].schema(), other.motor_sator_winding_temp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.iron_temp)) {
        this.iron_temp = data().deepCopy(fields()[2].schema(), other.iron_temp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.cooling_air_temp)) {
        this.cooling_air_temp = data().deepCopy(fields()[3].schema(), other.cooling_air_temp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.air_temp)) {
        this.air_temp = data().deepCopy(fields()[4].schema(), other.air_temp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.motor_power_supply_current)) {
        this.motor_power_supply_current = data().deepCopy(fields()[5].schema(), other.motor_power_supply_current);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing EngineSensor instance
     * @param other The existing instance to copy.
     */
    private Builder(com.manning.pulsar.iiot.engine.EngineSensor other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.motor_sator_winding_temp)) {
        this.motor_sator_winding_temp = data().deepCopy(fields()[1].schema(), other.motor_sator_winding_temp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.iron_temp)) {
        this.iron_temp = data().deepCopy(fields()[2].schema(), other.iron_temp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cooling_air_temp)) {
        this.cooling_air_temp = data().deepCopy(fields()[3].schema(), other.cooling_air_temp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.air_temp)) {
        this.air_temp = data().deepCopy(fields()[4].schema(), other.air_temp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.motor_power_supply_current)) {
        this.motor_power_supply_current = data().deepCopy(fields()[5].schema(), other.motor_power_supply_current);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * @return The value.
      */
    public int getSensorId() {
      return sensor_id;
    }


    /**
      * Sets the value of the 'sensor_id' field.
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setSensorId(int value) {
      validate(fields()[0], value);
      this.sensor_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearSensorId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'motor_sator_winding_temp' field.
      * @return The value.
      */
    public double getMotorSatorWindingTemp() {
      return motor_sator_winding_temp;
    }


    /**
      * Sets the value of the 'motor_sator_winding_temp' field.
      * @param value The value of 'motor_sator_winding_temp'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setMotorSatorWindingTemp(double value) {
      validate(fields()[1], value);
      this.motor_sator_winding_temp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'motor_sator_winding_temp' field has been set.
      * @return True if the 'motor_sator_winding_temp' field has been set, false otherwise.
      */
    public boolean hasMotorSatorWindingTemp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'motor_sator_winding_temp' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearMotorSatorWindingTemp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'iron_temp' field.
      * @return The value.
      */
    public double getIronTemp() {
      return iron_temp;
    }


    /**
      * Sets the value of the 'iron_temp' field.
      * @param value The value of 'iron_temp'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setIronTemp(double value) {
      validate(fields()[2], value);
      this.iron_temp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'iron_temp' field has been set.
      * @return True if the 'iron_temp' field has been set, false otherwise.
      */
    public boolean hasIronTemp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'iron_temp' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearIronTemp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'cooling_air_temp' field.
      * @return The value.
      */
    public double getCoolingAirTemp() {
      return cooling_air_temp;
    }


    /**
      * Sets the value of the 'cooling_air_temp' field.
      * @param value The value of 'cooling_air_temp'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setCoolingAirTemp(double value) {
      validate(fields()[3], value);
      this.cooling_air_temp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'cooling_air_temp' field has been set.
      * @return True if the 'cooling_air_temp' field has been set, false otherwise.
      */
    public boolean hasCoolingAirTemp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'cooling_air_temp' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearCoolingAirTemp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'air_temp' field.
      * @return The value.
      */
    public double getAirTemp() {
      return air_temp;
    }


    /**
      * Sets the value of the 'air_temp' field.
      * @param value The value of 'air_temp'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setAirTemp(double value) {
      validate(fields()[4], value);
      this.air_temp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'air_temp' field has been set.
      * @return True if the 'air_temp' field has been set, false otherwise.
      */
    public boolean hasAirTemp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'air_temp' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearAirTemp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'motor_power_supply_current' field.
      * @return The value.
      */
    public double getMotorPowerSupplyCurrent() {
      return motor_power_supply_current;
    }


    /**
      * Sets the value of the 'motor_power_supply_current' field.
      * @param value The value of 'motor_power_supply_current'.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder setMotorPowerSupplyCurrent(double value) {
      validate(fields()[5], value);
      this.motor_power_supply_current = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'motor_power_supply_current' field has been set.
      * @return True if the 'motor_power_supply_current' field has been set, false otherwise.
      */
    public boolean hasMotorPowerSupplyCurrent() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'motor_power_supply_current' field.
      * @return This builder.
      */
    public com.manning.pulsar.iiot.engine.EngineSensor.Builder clearMotorPowerSupplyCurrent() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EngineSensor build() {
      try {
        EngineSensor record = new EngineSensor();
        record.sensor_id = fieldSetFlags()[0] ? this.sensor_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.motor_sator_winding_temp = fieldSetFlags()[1] ? this.motor_sator_winding_temp : (java.lang.Double) defaultValue(fields()[1]);
        record.iron_temp = fieldSetFlags()[2] ? this.iron_temp : (java.lang.Double) defaultValue(fields()[2]);
        record.cooling_air_temp = fieldSetFlags()[3] ? this.cooling_air_temp : (java.lang.Double) defaultValue(fields()[3]);
        record.air_temp = fieldSetFlags()[4] ? this.air_temp : (java.lang.Double) defaultValue(fields()[4]);
        record.motor_power_supply_current = fieldSetFlags()[5] ? this.motor_power_supply_current : (java.lang.Double) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EngineSensor>
    WRITER$ = (org.apache.avro.io.DatumWriter<EngineSensor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EngineSensor>
    READER$ = (org.apache.avro.io.DatumReader<EngineSensor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.sensor_id);

    out.writeDouble(this.motor_sator_winding_temp);

    out.writeDouble(this.iron_temp);

    out.writeDouble(this.cooling_air_temp);

    out.writeDouble(this.air_temp);

    out.writeDouble(this.motor_power_supply_current);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensor_id = in.readInt();

      this.motor_sator_winding_temp = in.readDouble();

      this.iron_temp = in.readDouble();

      this.cooling_air_temp = in.readDouble();

      this.air_temp = in.readDouble();

      this.motor_power_supply_current = in.readDouble();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensor_id = in.readInt();
          break;

        case 1:
          this.motor_sator_winding_temp = in.readDouble();
          break;

        case 2:
          this.iron_temp = in.readDouble();
          break;

        case 3:
          this.cooling_air_temp = in.readDouble();
          break;

        case 4:
          this.air_temp = in.readDouble();
          break;

        case 5:
          this.motor_power_supply_current = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










