/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.order;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FoodOrderMeta extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4651593407591847838L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FoodOrderMeta\",\"namespace\":\"com.gottaeat.domain.order\",\"fields\":[{\"name\":\"order_id\",\"type\":\"long\"},{\"name\":\"customer_id\",\"type\":\"long\"},{\"name\":\"time_placed\",\"type\":\"string\"},{\"name\":\"order_status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"NEW\",\"VALIDATED\",\"ACCEPTED\",\"READY\",\"DISPATCHED\",\"DELIVERED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FoodOrderMeta> ENCODER =
      new BinaryMessageEncoder<FoodOrderMeta>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FoodOrderMeta> DECODER =
      new BinaryMessageDecoder<FoodOrderMeta>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FoodOrderMeta> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FoodOrderMeta> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FoodOrderMeta> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FoodOrderMeta>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FoodOrderMeta to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FoodOrderMeta from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FoodOrderMeta instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FoodOrderMeta fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long order_id;
  @Deprecated public long customer_id;
  @Deprecated public java.lang.CharSequence time_placed;
  @Deprecated public com.gottaeat.domain.order.OrderStatus order_status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FoodOrderMeta() {}

  /**
   * All-args constructor.
   * @param order_id The new value for order_id
   * @param customer_id The new value for customer_id
   * @param time_placed The new value for time_placed
   * @param order_status The new value for order_status
   */
  public FoodOrderMeta(java.lang.Long order_id, java.lang.Long customer_id, java.lang.CharSequence time_placed, com.gottaeat.domain.order.OrderStatus order_status) {
    this.order_id = order_id;
    this.customer_id = customer_id;
    this.time_placed = time_placed;
    this.order_status = order_status;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return order_id;
    case 1: return customer_id;
    case 2: return time_placed;
    case 3: return order_status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: order_id = (java.lang.Long)value$; break;
    case 1: customer_id = (java.lang.Long)value$; break;
    case 2: time_placed = (java.lang.CharSequence)value$; break;
    case 3: order_status = (com.gottaeat.domain.order.OrderStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'order_id' field.
   * @return The value of the 'order_id' field.
   */
  public long getOrderId() {
    return order_id;
  }


  /**
   * Sets the value of the 'order_id' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.order_id = value;
  }

  /**
   * Gets the value of the 'customer_id' field.
   * @return The value of the 'customer_id' field.
   */
  public long getCustomerId() {
    return customer_id;
  }


  /**
   * Sets the value of the 'customer_id' field.
   * @param value the value to set.
   */
  public void setCustomerId(long value) {
    this.customer_id = value;
  }

  /**
   * Gets the value of the 'time_placed' field.
   * @return The value of the 'time_placed' field.
   */
  public java.lang.CharSequence getTimePlaced() {
    return time_placed;
  }


  /**
   * Sets the value of the 'time_placed' field.
   * @param value the value to set.
   */
  public void setTimePlaced(java.lang.CharSequence value) {
    this.time_placed = value;
  }

  /**
   * Gets the value of the 'order_status' field.
   * @return The value of the 'order_status' field.
   */
  public com.gottaeat.domain.order.OrderStatus getOrderStatus() {
    return order_status;
  }


  /**
   * Sets the value of the 'order_status' field.
   * @param value the value to set.
   */
  public void setOrderStatus(com.gottaeat.domain.order.OrderStatus value) {
    this.order_status = value;
  }

  /**
   * Creates a new FoodOrderMeta RecordBuilder.
   * @return A new FoodOrderMeta RecordBuilder
   */
  public static com.gottaeat.domain.order.FoodOrderMeta.Builder newBuilder() {
    return new com.gottaeat.domain.order.FoodOrderMeta.Builder();
  }

  /**
   * Creates a new FoodOrderMeta RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FoodOrderMeta RecordBuilder
   */
  public static com.gottaeat.domain.order.FoodOrderMeta.Builder newBuilder(com.gottaeat.domain.order.FoodOrderMeta.Builder other) {
    if (other == null) {
      return new com.gottaeat.domain.order.FoodOrderMeta.Builder();
    } else {
      return new com.gottaeat.domain.order.FoodOrderMeta.Builder(other);
    }
  }

  /**
   * Creates a new FoodOrderMeta RecordBuilder by copying an existing FoodOrderMeta instance.
   * @param other The existing instance to copy.
   * @return A new FoodOrderMeta RecordBuilder
   */
  public static com.gottaeat.domain.order.FoodOrderMeta.Builder newBuilder(com.gottaeat.domain.order.FoodOrderMeta other) {
    if (other == null) {
      return new com.gottaeat.domain.order.FoodOrderMeta.Builder();
    } else {
      return new com.gottaeat.domain.order.FoodOrderMeta.Builder(other);
    }
  }

  /**
   * RecordBuilder for FoodOrderMeta instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FoodOrderMeta>
    implements org.apache.avro.data.RecordBuilder<FoodOrderMeta> {

    private long order_id;
    private long customer_id;
    private java.lang.CharSequence time_placed;
    private com.gottaeat.domain.order.OrderStatus order_status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gottaeat.domain.order.FoodOrderMeta.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.order_id)) {
        this.order_id = data().deepCopy(fields()[0].schema(), other.order_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[1].schema(), other.customer_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.time_placed)) {
        this.time_placed = data().deepCopy(fields()[2].schema(), other.time_placed);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.order_status)) {
        this.order_status = data().deepCopy(fields()[3].schema(), other.order_status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing FoodOrderMeta instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gottaeat.domain.order.FoodOrderMeta other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.order_id)) {
        this.order_id = data().deepCopy(fields()[0].schema(), other.order_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[1].schema(), other.customer_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.time_placed)) {
        this.time_placed = data().deepCopy(fields()[2].schema(), other.time_placed);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.order_status)) {
        this.order_status = data().deepCopy(fields()[3].schema(), other.order_status);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'order_id' field.
      * @return The value.
      */
    public long getOrderId() {
      return order_id;
    }


    /**
      * Sets the value of the 'order_id' field.
      * @param value The value of 'order_id'.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder setOrderId(long value) {
      validate(fields()[0], value);
      this.order_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'order_id' field has been set.
      * @return True if the 'order_id' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'order_id' field.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_id' field.
      * @return The value.
      */
    public long getCustomerId() {
      return customer_id;
    }


    /**
      * Sets the value of the 'customer_id' field.
      * @param value The value of 'customer_id'.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder setCustomerId(long value) {
      validate(fields()[1], value);
      this.customer_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_id' field has been set.
      * @return True if the 'customer_id' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customer_id' field.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder clearCustomerId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'time_placed' field.
      * @return The value.
      */
    public java.lang.CharSequence getTimePlaced() {
      return time_placed;
    }


    /**
      * Sets the value of the 'time_placed' field.
      * @param value The value of 'time_placed'.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder setTimePlaced(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.time_placed = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'time_placed' field has been set.
      * @return True if the 'time_placed' field has been set, false otherwise.
      */
    public boolean hasTimePlaced() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'time_placed' field.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder clearTimePlaced() {
      time_placed = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'order_status' field.
      * @return The value.
      */
    public com.gottaeat.domain.order.OrderStatus getOrderStatus() {
      return order_status;
    }


    /**
      * Sets the value of the 'order_status' field.
      * @param value The value of 'order_status'.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder setOrderStatus(com.gottaeat.domain.order.OrderStatus value) {
      validate(fields()[3], value);
      this.order_status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'order_status' field has been set.
      * @return True if the 'order_status' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'order_status' field.
      * @return This builder.
      */
    public com.gottaeat.domain.order.FoodOrderMeta.Builder clearOrderStatus() {
      order_status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FoodOrderMeta build() {
      try {
        FoodOrderMeta record = new FoodOrderMeta();
        record.order_id = fieldSetFlags()[0] ? this.order_id : (java.lang.Long) defaultValue(fields()[0]);
        record.customer_id = fieldSetFlags()[1] ? this.customer_id : (java.lang.Long) defaultValue(fields()[1]);
        record.time_placed = fieldSetFlags()[2] ? this.time_placed : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.order_status = fieldSetFlags()[3] ? this.order_status : (com.gottaeat.domain.order.OrderStatus) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FoodOrderMeta>
    WRITER$ = (org.apache.avro.io.DatumWriter<FoodOrderMeta>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FoodOrderMeta>
    READER$ = (org.apache.avro.io.DatumReader<FoodOrderMeta>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.order_id);

    out.writeLong(this.customer_id);

    out.writeString(this.time_placed);

    out.writeEnum(this.order_status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.order_id = in.readLong();

      this.customer_id = in.readLong();

      this.time_placed = in.readString(this.time_placed instanceof Utf8 ? (Utf8)this.time_placed : null);

      this.order_status = com.gottaeat.domain.order.OrderStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.order_id = in.readLong();
          break;

        case 1:
          this.customer_id = in.readLong();
          break;

        case 2:
          this.time_placed = in.readString(this.time_placed instanceof Utf8 ? (Utf8)this.time_placed : null);
          break;

        case 3:
          this.order_status = com.gottaeat.domain.order.OrderStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










