/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.resturant;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MenuItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6779108159857626441L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MenuItem\",\"namespace\":\"com.gottaeat.domain.resturant\",\"fields\":[{\"name\":\"item_id\",\"type\":\"long\"},{\"name\":\"item_name\",\"type\":\"string\"},{\"name\":\"item_description\",\"type\":\"string\"},{\"name\":\"customizations\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[\"\"]},{\"name\":\"price\",\"type\":\"float\"},{\"name\":\"taxable\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MenuItem> ENCODER =
      new BinaryMessageEncoder<MenuItem>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MenuItem> DECODER =
      new BinaryMessageDecoder<MenuItem>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MenuItem> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MenuItem> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MenuItem> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MenuItem>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MenuItem to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MenuItem from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MenuItem instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MenuItem fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long item_id;
  @Deprecated public java.lang.CharSequence item_name;
  @Deprecated public java.lang.CharSequence item_description;
  @Deprecated public java.util.List<java.lang.CharSequence> customizations;
  @Deprecated public float price;
  @Deprecated public boolean taxable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MenuItem() {}

  /**
   * All-args constructor.
   * @param item_id The new value for item_id
   * @param item_name The new value for item_name
   * @param item_description The new value for item_description
   * @param customizations The new value for customizations
   * @param price The new value for price
   * @param taxable The new value for taxable
   */
  public MenuItem(java.lang.Long item_id, java.lang.CharSequence item_name, java.lang.CharSequence item_description, java.util.List<java.lang.CharSequence> customizations, java.lang.Float price, java.lang.Boolean taxable) {
    this.item_id = item_id;
    this.item_name = item_name;
    this.item_description = item_description;
    this.customizations = customizations;
    this.price = price;
    this.taxable = taxable;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return item_id;
    case 1: return item_name;
    case 2: return item_description;
    case 3: return customizations;
    case 4: return price;
    case 5: return taxable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: item_id = (java.lang.Long)value$; break;
    case 1: item_name = (java.lang.CharSequence)value$; break;
    case 2: item_description = (java.lang.CharSequence)value$; break;
    case 3: customizations = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: price = (java.lang.Float)value$; break;
    case 5: taxable = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'item_id' field.
   * @return The value of the 'item_id' field.
   */
  public long getItemId() {
    return item_id;
  }


  /**
   * Sets the value of the 'item_id' field.
   * @param value the value to set.
   */
  public void setItemId(long value) {
    this.item_id = value;
  }

  /**
   * Gets the value of the 'item_name' field.
   * @return The value of the 'item_name' field.
   */
  public java.lang.CharSequence getItemName() {
    return item_name;
  }


  /**
   * Sets the value of the 'item_name' field.
   * @param value the value to set.
   */
  public void setItemName(java.lang.CharSequence value) {
    this.item_name = value;
  }

  /**
   * Gets the value of the 'item_description' field.
   * @return The value of the 'item_description' field.
   */
  public java.lang.CharSequence getItemDescription() {
    return item_description;
  }


  /**
   * Sets the value of the 'item_description' field.
   * @param value the value to set.
   */
  public void setItemDescription(java.lang.CharSequence value) {
    this.item_description = value;
  }

  /**
   * Gets the value of the 'customizations' field.
   * @return The value of the 'customizations' field.
   */
  public java.util.List<java.lang.CharSequence> getCustomizations() {
    return customizations;
  }


  /**
   * Sets the value of the 'customizations' field.
   * @param value the value to set.
   */
  public void setCustomizations(java.util.List<java.lang.CharSequence> value) {
    this.customizations = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public float getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(float value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'taxable' field.
   * @return The value of the 'taxable' field.
   */
  public boolean getTaxable() {
    return taxable;
  }


  /**
   * Sets the value of the 'taxable' field.
   * @param value the value to set.
   */
  public void setTaxable(boolean value) {
    this.taxable = value;
  }

  /**
   * Creates a new MenuItem RecordBuilder.
   * @return A new MenuItem RecordBuilder
   */
  public static com.gottaeat.domain.resturant.MenuItem.Builder newBuilder() {
    return new com.gottaeat.domain.resturant.MenuItem.Builder();
  }

  /**
   * Creates a new MenuItem RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MenuItem RecordBuilder
   */
  public static com.gottaeat.domain.resturant.MenuItem.Builder newBuilder(com.gottaeat.domain.resturant.MenuItem.Builder other) {
    if (other == null) {
      return new com.gottaeat.domain.resturant.MenuItem.Builder();
    } else {
      return new com.gottaeat.domain.resturant.MenuItem.Builder(other);
    }
  }

  /**
   * Creates a new MenuItem RecordBuilder by copying an existing MenuItem instance.
   * @param other The existing instance to copy.
   * @return A new MenuItem RecordBuilder
   */
  public static com.gottaeat.domain.resturant.MenuItem.Builder newBuilder(com.gottaeat.domain.resturant.MenuItem other) {
    if (other == null) {
      return new com.gottaeat.domain.resturant.MenuItem.Builder();
    } else {
      return new com.gottaeat.domain.resturant.MenuItem.Builder(other);
    }
  }

  /**
   * RecordBuilder for MenuItem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MenuItem>
    implements org.apache.avro.data.RecordBuilder<MenuItem> {

    private long item_id;
    private java.lang.CharSequence item_name;
    private java.lang.CharSequence item_description;
    private java.util.List<java.lang.CharSequence> customizations;
    private float price;
    private boolean taxable;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gottaeat.domain.resturant.MenuItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.item_id)) {
        this.item_id = data().deepCopy(fields()[0].schema(), other.item_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.item_name)) {
        this.item_name = data().deepCopy(fields()[1].schema(), other.item_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.item_description)) {
        this.item_description = data().deepCopy(fields()[2].schema(), other.item_description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.customizations)) {
        this.customizations = data().deepCopy(fields()[3].schema(), other.customizations);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.taxable)) {
        this.taxable = data().deepCopy(fields()[5].schema(), other.taxable);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing MenuItem instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gottaeat.domain.resturant.MenuItem other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.item_id)) {
        this.item_id = data().deepCopy(fields()[0].schema(), other.item_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.item_name)) {
        this.item_name = data().deepCopy(fields()[1].schema(), other.item_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.item_description)) {
        this.item_description = data().deepCopy(fields()[2].schema(), other.item_description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customizations)) {
        this.customizations = data().deepCopy(fields()[3].schema(), other.customizations);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.taxable)) {
        this.taxable = data().deepCopy(fields()[5].schema(), other.taxable);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'item_id' field.
      * @return The value.
      */
    public long getItemId() {
      return item_id;
    }


    /**
      * Sets the value of the 'item_id' field.
      * @param value The value of 'item_id'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setItemId(long value) {
      validate(fields()[0], value);
      this.item_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'item_id' field has been set.
      * @return True if the 'item_id' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'item_id' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearItemId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'item_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemName() {
      return item_name;
    }


    /**
      * Sets the value of the 'item_name' field.
      * @param value The value of 'item_name'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setItemName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.item_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'item_name' field has been set.
      * @return True if the 'item_name' field has been set, false otherwise.
      */
    public boolean hasItemName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'item_name' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearItemName() {
      item_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'item_description' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemDescription() {
      return item_description;
    }


    /**
      * Sets the value of the 'item_description' field.
      * @param value The value of 'item_description'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setItemDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.item_description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'item_description' field has been set.
      * @return True if the 'item_description' field has been set, false otherwise.
      */
    public boolean hasItemDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'item_description' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearItemDescription() {
      item_description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'customizations' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getCustomizations() {
      return customizations;
    }


    /**
      * Sets the value of the 'customizations' field.
      * @param value The value of 'customizations'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setCustomizations(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.customizations = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'customizations' field has been set.
      * @return True if the 'customizations' field has been set, false otherwise.
      */
    public boolean hasCustomizations() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'customizations' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearCustomizations() {
      customizations = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public float getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setPrice(float value) {
      validate(fields()[4], value);
      this.price = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearPrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'taxable' field.
      * @return The value.
      */
    public boolean getTaxable() {
      return taxable;
    }


    /**
      * Sets the value of the 'taxable' field.
      * @param value The value of 'taxable'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder setTaxable(boolean value) {
      validate(fields()[5], value);
      this.taxable = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'taxable' field has been set.
      * @return True if the 'taxable' field has been set, false otherwise.
      */
    public boolean hasTaxable() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'taxable' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.MenuItem.Builder clearTaxable() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MenuItem build() {
      try {
        MenuItem record = new MenuItem();
        record.item_id = fieldSetFlags()[0] ? this.item_id : (java.lang.Long) defaultValue(fields()[0]);
        record.item_name = fieldSetFlags()[1] ? this.item_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.item_description = fieldSetFlags()[2] ? this.item_description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.customizations = fieldSetFlags()[3] ? this.customizations : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        record.price = fieldSetFlags()[4] ? this.price : (java.lang.Float) defaultValue(fields()[4]);
        record.taxable = fieldSetFlags()[5] ? this.taxable : (java.lang.Boolean) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MenuItem>
    WRITER$ = (org.apache.avro.io.DatumWriter<MenuItem>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MenuItem>
    READER$ = (org.apache.avro.io.DatumReader<MenuItem>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.item_id);

    out.writeString(this.item_name);

    out.writeString(this.item_description);

    long size0 = this.customizations.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.customizations) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeFloat(this.price);

    out.writeBoolean(this.taxable);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.item_id = in.readLong();

      this.item_name = in.readString(this.item_name instanceof Utf8 ? (Utf8)this.item_name : null);

      this.item_description = in.readString(this.item_description instanceof Utf8 ? (Utf8)this.item_description : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.customizations;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("customizations").schema());
        this.customizations = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.price = in.readFloat();

      this.taxable = in.readBoolean();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.item_id = in.readLong();
          break;

        case 1:
          this.item_name = in.readString(this.item_name instanceof Utf8 ? (Utf8)this.item_name : null);
          break;

        case 2:
          this.item_description = in.readString(this.item_description instanceof Utf8 ? (Utf8)this.item_description : null);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.customizations;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("customizations").schema());
            this.customizations = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 4:
          this.price = in.readFloat();
          break;

        case 5:
          this.taxable = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










