/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.resturant;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Resturant extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4942770633887967710L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Resturant\",\"namespace\":\"com.gottaeat.domain.resturant\",\"fields\":[{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.gottaeat.domain.common\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"},{\"name\":\"geo\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LatLon\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Resturant> ENCODER =
      new BinaryMessageEncoder<Resturant>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Resturant> DECODER =
      new BinaryMessageDecoder<Resturant>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Resturant> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Resturant> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Resturant> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Resturant>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Resturant to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Resturant from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Resturant instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Resturant fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.gottaeat.domain.common.Address location;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Resturant() {}

  /**
   * All-args constructor.
   * @param location The new value for location
   */
  public Resturant(com.gottaeat.domain.common.Address location) {
    this.location = location;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return location;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: location = (com.gottaeat.domain.common.Address)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public com.gottaeat.domain.common.Address getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(com.gottaeat.domain.common.Address value) {
    this.location = value;
  }

  /**
   * Creates a new Resturant RecordBuilder.
   * @return A new Resturant RecordBuilder
   */
  public static com.gottaeat.domain.resturant.Resturant.Builder newBuilder() {
    return new com.gottaeat.domain.resturant.Resturant.Builder();
  }

  /**
   * Creates a new Resturant RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Resturant RecordBuilder
   */
  public static com.gottaeat.domain.resturant.Resturant.Builder newBuilder(com.gottaeat.domain.resturant.Resturant.Builder other) {
    if (other == null) {
      return new com.gottaeat.domain.resturant.Resturant.Builder();
    } else {
      return new com.gottaeat.domain.resturant.Resturant.Builder(other);
    }
  }

  /**
   * Creates a new Resturant RecordBuilder by copying an existing Resturant instance.
   * @param other The existing instance to copy.
   * @return A new Resturant RecordBuilder
   */
  public static com.gottaeat.domain.resturant.Resturant.Builder newBuilder(com.gottaeat.domain.resturant.Resturant other) {
    if (other == null) {
      return new com.gottaeat.domain.resturant.Resturant.Builder();
    } else {
      return new com.gottaeat.domain.resturant.Resturant.Builder(other);
    }
  }

  /**
   * RecordBuilder for Resturant instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Resturant>
    implements org.apache.avro.data.RecordBuilder<Resturant> {

    private com.gottaeat.domain.common.Address location;
    private com.gottaeat.domain.common.Address.Builder locationBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gottaeat.domain.resturant.Resturant.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = com.gottaeat.domain.common.Address.newBuilder(other.getLocationBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Resturant instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gottaeat.domain.resturant.Resturant other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = true;
      }
      this.locationBuilder = null;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public com.gottaeat.domain.common.Address getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.Resturant.Builder setLocation(com.gottaeat.domain.common.Address value) {
      validate(fields()[0], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.gottaeat.domain.common.Address.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(com.gottaeat.domain.common.Address.newBuilder(location));
        } else {
          setLocationBuilder(com.gottaeat.domain.common.Address.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.gottaeat.domain.resturant.Resturant.Builder setLocationBuilder(com.gottaeat.domain.common.Address.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.gottaeat.domain.resturant.Resturant.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Resturant build() {
      try {
        Resturant record = new Resturant();
        if (locationBuilder != null) {
          try {
            record.location = this.locationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("location"));
            throw e;
          }
        } else {
          record.location = fieldSetFlags()[0] ? this.location : (com.gottaeat.domain.common.Address) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Resturant>
    WRITER$ = (org.apache.avro.io.DatumWriter<Resturant>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Resturant>
    READER$ = (org.apache.avro.io.DatumReader<Resturant>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.location.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.location == null) {
        this.location = new com.gottaeat.domain.common.Address();
      }
      this.location.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.location == null) {
            this.location = new com.gottaeat.domain.common.Address();
          }
          this.location.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










