/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gottaeat.domain.payment;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ElectronicCheck extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8503863986694583974L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ElectronicCheck\",\"namespace\":\"com.gottaeat.domain.payment\",\"fields\":[{\"name\":\"routingNumber\",\"type\":\"string\"},{\"name\":\"accountNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ElectronicCheck> ENCODER =
      new BinaryMessageEncoder<ElectronicCheck>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ElectronicCheck> DECODER =
      new BinaryMessageDecoder<ElectronicCheck>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ElectronicCheck> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ElectronicCheck> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ElectronicCheck> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ElectronicCheck>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ElectronicCheck to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ElectronicCheck from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ElectronicCheck instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ElectronicCheck fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence routingNumber;
  @Deprecated public java.lang.CharSequence accountNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ElectronicCheck() {}

  /**
   * All-args constructor.
   * @param routingNumber The new value for routingNumber
   * @param accountNumber The new value for accountNumber
   */
  public ElectronicCheck(java.lang.CharSequence routingNumber, java.lang.CharSequence accountNumber) {
    this.routingNumber = routingNumber;
    this.accountNumber = accountNumber;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return routingNumber;
    case 1: return accountNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: routingNumber = (java.lang.CharSequence)value$; break;
    case 1: accountNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'routingNumber' field.
   * @return The value of the 'routingNumber' field.
   */
  public java.lang.CharSequence getRoutingNumber() {
    return routingNumber;
  }


  /**
   * Sets the value of the 'routingNumber' field.
   * @param value the value to set.
   */
  public void setRoutingNumber(java.lang.CharSequence value) {
    this.routingNumber = value;
  }

  /**
   * Gets the value of the 'accountNumber' field.
   * @return The value of the 'accountNumber' field.
   */
  public java.lang.CharSequence getAccountNumber() {
    return accountNumber;
  }


  /**
   * Sets the value of the 'accountNumber' field.
   * @param value the value to set.
   */
  public void setAccountNumber(java.lang.CharSequence value) {
    this.accountNumber = value;
  }

  /**
   * Creates a new ElectronicCheck RecordBuilder.
   * @return A new ElectronicCheck RecordBuilder
   */
  public static com.gottaeat.domain.payment.ElectronicCheck.Builder newBuilder() {
    return new com.gottaeat.domain.payment.ElectronicCheck.Builder();
  }

  /**
   * Creates a new ElectronicCheck RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ElectronicCheck RecordBuilder
   */
  public static com.gottaeat.domain.payment.ElectronicCheck.Builder newBuilder(com.gottaeat.domain.payment.ElectronicCheck.Builder other) {
    if (other == null) {
      return new com.gottaeat.domain.payment.ElectronicCheck.Builder();
    } else {
      return new com.gottaeat.domain.payment.ElectronicCheck.Builder(other);
    }
  }

  /**
   * Creates a new ElectronicCheck RecordBuilder by copying an existing ElectronicCheck instance.
   * @param other The existing instance to copy.
   * @return A new ElectronicCheck RecordBuilder
   */
  public static com.gottaeat.domain.payment.ElectronicCheck.Builder newBuilder(com.gottaeat.domain.payment.ElectronicCheck other) {
    if (other == null) {
      return new com.gottaeat.domain.payment.ElectronicCheck.Builder();
    } else {
      return new com.gottaeat.domain.payment.ElectronicCheck.Builder(other);
    }
  }

  /**
   * RecordBuilder for ElectronicCheck instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ElectronicCheck>
    implements org.apache.avro.data.RecordBuilder<ElectronicCheck> {

    private java.lang.CharSequence routingNumber;
    private java.lang.CharSequence accountNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gottaeat.domain.payment.ElectronicCheck.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.routingNumber)) {
        this.routingNumber = data().deepCopy(fields()[0].schema(), other.routingNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[1].schema(), other.accountNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ElectronicCheck instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gottaeat.domain.payment.ElectronicCheck other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.routingNumber)) {
        this.routingNumber = data().deepCopy(fields()[0].schema(), other.routingNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[1].schema(), other.accountNumber);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'routingNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getRoutingNumber() {
      return routingNumber;
    }


    /**
      * Sets the value of the 'routingNumber' field.
      * @param value The value of 'routingNumber'.
      * @return This builder.
      */
    public com.gottaeat.domain.payment.ElectronicCheck.Builder setRoutingNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.routingNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'routingNumber' field has been set.
      * @return True if the 'routingNumber' field has been set, false otherwise.
      */
    public boolean hasRoutingNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'routingNumber' field.
      * @return This builder.
      */
    public com.gottaeat.domain.payment.ElectronicCheck.Builder clearRoutingNumber() {
      routingNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountNumber() {
      return accountNumber;
    }


    /**
      * Sets the value of the 'accountNumber' field.
      * @param value The value of 'accountNumber'.
      * @return This builder.
      */
    public com.gottaeat.domain.payment.ElectronicCheck.Builder setAccountNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.accountNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'accountNumber' field has been set.
      * @return True if the 'accountNumber' field has been set, false otherwise.
      */
    public boolean hasAccountNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'accountNumber' field.
      * @return This builder.
      */
    public com.gottaeat.domain.payment.ElectronicCheck.Builder clearAccountNumber() {
      accountNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ElectronicCheck build() {
      try {
        ElectronicCheck record = new ElectronicCheck();
        record.routingNumber = fieldSetFlags()[0] ? this.routingNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.accountNumber = fieldSetFlags()[1] ? this.accountNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ElectronicCheck>
    WRITER$ = (org.apache.avro.io.DatumWriter<ElectronicCheck>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ElectronicCheck>
    READER$ = (org.apache.avro.io.DatumReader<ElectronicCheck>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.routingNumber);

    out.writeString(this.accountNumber);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.routingNumber = in.readString(this.routingNumber instanceof Utf8 ? (Utf8)this.routingNumber : null);

      this.accountNumber = in.readString(this.accountNumber instanceof Utf8 ? (Utf8)this.accountNumber : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.routingNumber = in.readString(this.routingNumber instanceof Utf8 ? (Utf8)this.routingNumber : null);
          break;

        case 1:
          this.accountNumber = in.readString(this.accountNumber instanceof Utf8 ? (Utf8)this.accountNumber : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










